spring:
    boot:
      admin:
        client:
          url: http://${eureka.instance.hostname}:${eureka.instance.port}/admin/
          auto-registration: true
    application:
        name: Cindercloud-whitehat
    datasource:
        url: jdbc:postgresql://localhost:5432/cindercloud
        username: cindercloud
        password: cindercloud
        driver-class-name: org.postgresql.Driver
        type: com.zaxxer.hikari.HikariDataSource
        hikari:
          validation-timeout: 3000
          minimum-idle: 1
          idle-timeout: 10000
          maximum-pool-size: 5

#logging
logging:
  level:
    org:
      springframework: info
    cloud:
      cinder: DEBUG

cloud:
  cinder:
    mailgun:
      api-key: 'api-xxx'
      domain: cinder.cloud
      default-to: info@cinder.cloud
    whitehat:
      tiny-gas-price: 5000000000
      low-gas-price: 50000000000
      medium-gas-price: 500000000000
      high-gas-price: 8000000000000
      address: '0x08101434C81e868DcF1E428F49118239B7022AC4'
management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: env,shutdown,threaddump,configprops
  endpoint:
    health:
      show-details: ALWAYS
eureka:
  instance:
    hostname: localhost
    port: 8761
    appname: cindercloud-wallet
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true

ribbon:
  eureka:
    enabled: true
  restclient:
    enabled: true
  client:
    name: client
  ConnectTimeout: 100000
  ReadTimeout: 100000
