spring:
  application:
    name: Cindercloud-whitehat
  datasource:
    url: jdbc:postgresql://localhost:5432/cindercloud
    username: cindercloud
    password: cindercloud
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      validation-timeout: 3000
      minimum-idle: 1
      idle-timeout: 10000
      maximum-pool-size: 5

#logging
logging:
  level:
    org:
      springframework: info
    cloud:
      cinder: DEBUG

cloud:
  cinder:
    mailgun:
      api-key: 'api-xxx'
      domain: cinder.cloud
      default-to: info@cinder.cloud
    whitehat:
      tiny-gas-price: 5000000000
      low-gas-price: 50000000000
      medium-gas-price: 500000000000
      high-gas-price: 8000000000000
      address: '0x08101434C81e868DcF1E428F49118239B7022AC4'
management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: env,shutdown,threaddump,configprops
  endpoint:
    health:
      show-details: ALWAYS
ribbon:
  restclient:
    enabled: true
  client:
    name: client
  ConnectTimeout: 100000
  ReadTimeout: 100000

contracts:
  deltabalances:
    address: '0x40a38911e470fC088bEEb1a9480c2d69C847BCeC'
  parity:
    signature-registry:
      address: '0x44691B39d1a75dC4E0A0346CBB15E310e6ED1E86'