cloud:
  cinder:
    ethereum:
      endpoint:
        url: wss://ethereum-ws2.arkane.network
        websocket-url: wss://ethereum-ws.arkane.network
    queue:
      block-added: cindercloud_mainnet
      user-token-import: mainnet_user_token_import