spring:
  application:
    name: Cindercloud-importer
  datasource:
    url: jdbc:postgresql://localhost:5432/cindercloud
    username: cindercloud
    password: cindercloud
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      validation-timeout: 3000
      minimum-idle: 2
      idle-timeout: 10000
      maximum-pool-size: 6
  rabbitmq:
    password: xxx
    username: cindercloud-worker
    virtual-host: cindercloud
    host: cindercloud-rabbitmq
    port: 5672
    listener:
      simple:
        concurrency: 10
#logging
logging:
  level:
    org:
      springframework: info
    cloud:
      cinder: DEBUG

cloud:
  cinder:
    transactions:
      historic-threshold: 500000
management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: env,shutdown,threaddump,configprops
  endpoint:
    health:
      show-details: ALWAYS
ribbon:
  restclient:
    enabled: true
  client:
    name: client
  ConnectTimeout: 100000
  ReadTimeout: 100000

contracts:
  parity:
    signature-registry:
      address: '0x44691B39d1a75dC4E0A0346CBB15E310e6ED1E86'
  deltabalances:
      address: '0x40a38911e470fC088bEEb1a9480c2d69C847BCeC'

