cloud:
  cinder:
    ethereum:
      endpoint:
        url: wss://ethereum-ws2.arkane.network
        websocket-url: wss://ws.cinder.cloud
    queue:
      block-added: cindercloud_mainnet_localhost
      user-token-import: mainnet_user_token_import